version: 2.1

executors:
  main-executor:
    docker:
      - image: circleci/node:lts

jobs:
  deploy:
    executor: main-executor
    parameters:
      clever-app-id:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: sudo npm install --global clever-tools
      - run:
          command: clever login --token=$CLEVER_TOKEN --secret=$CLEVER_SECRET
      - run:
          command: clever link << parameters.clever-app-id >>
      - run:
          command: clever deploy --force
  
workflows:
  version: 2

  deploy: 
    jobs:
      - deploy:
          clever-app-id: app_69c5464d-594e-4c48-863b-07cd050dbfe4
          context: clever-cloud-zenika
          filters:
            branches:
              only: deploy-to-staging
      - deploy:
          clever-app-id: app_2579b99e-f65c-4fc3-83b9-95082cde725f
          context: clever-cloud-zenika-dev
          filters:
            branches:
              only: master
